# Generated by Django 2.2.4 on 2019-10-02 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('piracy_prevention_api', '0002_profilefeeditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationList',
            fields=[
                ('activation_date', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateTimeField(auto_now_add=True)),
                ('auth_machine', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('activation_hash', models.CharField(default='100', max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_name', models.CharField(max_length=50, unique=True)),
                ('software_manufacturer', models.CharField(max_length=50)),
                ('active_users', models.ManyToManyField(through='piracy_prevention_api.ActivationList', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ProfileFeedItem',
        ),
        migrations.AddField(
            model_name='activationlist',
            name='software',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piracy_prevention_api.SoftwareProfile'),
        ),
        migrations.AddField(
            model_name='activationlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
