# Generated by Django 2.2.4 on 2019-10-03 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piracy_prevention_api', '0003_auto_20191002_0828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='softwareprofile',
            old_name='software_manufacturer',
            new_name='software_organization',
        ),
    ]
