# Generated by Django 2.2.4 on 2019-10-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piracy_prevention_api', '0005_auto_20191003_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationlist',
            name='activation_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='activationlist',
            name='activation_hash',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='activationlist',
            name='expiration_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
