# Generated by Django 2.2.4 on 2019-10-03 21:10

from django.db import migrations, models
import piracy_prevention_api.hashmaker


class Migration(migrations.Migration):

    dependencies = [
        ('piracy_prevention_api', '0006_auto_20191003_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationlist',
            name='activation_hash',
            field=models.CharField(default=piracy_prevention_api.hashmaker.Key, max_length=255, primary_key=True, serialize=False),
        ),
    ]
