# Generated by Django 2.2.4 on 2019-10-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piracy_prevention_api', '0007_auto_20191003_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='activationlist',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
    ]
