# Generated by Django 2.2.4 on 2019-11-07 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piracy_prevention_api', '0008_activationlist_is_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationlist',
            name='authorized_machine',
            field=models.UUIDField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='activationlist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
