# Generated by Django 2.2.4 on 2019-11-07 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piracy_prevention_api', '0009_auto_20191107_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
    ]
